### ISSUE TITLE
Canvas components uses variables from outside the component.

### ISSUE THREAD

**Issue by arol** [F-Smith/whats-that#51]
Canvas component uses this structure:

```jsx
let foo = false;

const Canvas = (props) => {
  foo = true;
}
```

This is wrong because the scope of the variable is outside the component. That won't be a problem if it's a constant shared between instances of the component (like `googleURL`), but it's not the case.

There's a comment on top of the variables definition block. Yesterday @GelenaB had problems with it already.

Move all definitions into the component and use `useState` or `useReducer`.

**Comment by gibsoncream** [comment]
Reviewed, move variables inside, closing the issue. 
`useReducer `to be completed
